name: macOS Build
on:
  push:
    branches:
 - main
  pull_request:
    branches:
 - main

jobs:
  build:
    runs-on: macOS-latest
    steps:
 - uses: actions/checkout@v2
 - name: Set up Xcode
        # Remove xcode-select --install since it's already installed
        run: sudo xcodebuild -license accept
 - name: Install Homebrew
        run: |
 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 - name: Install dependencies
        run: brew install cmake boost
 - name: Build project
        run: |
 mkdir build
 cd build
 cmake ..
 make
 - name: Run tests
        run: make test